# Generated by Django 4.2.2 on 2023-07-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repair_category",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Laptop Repair", "Laptop Repair"),
                            ("Phone Repair", "Phone Repair"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.CharField(max_length=50, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
