# Generated by Django 4.2.3 on 2023-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_alter_profile_means_of_identity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="means_of_identity",
            field=models.ImageField(null=True, upload_to="identityImage/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="particulars",
            field=models.ImageField(null=True, upload_to="particularsImage/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_passport",
            field=models.ImageField(null=True, upload_to="staffImage/"),
        ),
    ]
