# Generated by Django 4.2.3 on 2023-07-31 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consult",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=50)),
                ("complaint", models.CharField(max_length=300, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
