# Generated by Django 4.2.3 on 2023-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultapp", "0003_consult_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="consult",
            name="agent_incharge",
            field=models.CharField(
                choices=[
                    ("--------", ""),
                    ("admin", "admin"),
                    ("staff", "staff"),
                    ("user", "user"),
                    ("staff1", "staff1"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
