# Generated by Django 4.2.4 on 2023-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultapp", "0005_alter_consult_agent_incharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consult",
            name="agent_incharge",
            field=models.CharField(
                choices=[
                    ("--------", ""),
                    ("admin", "admin"),
                    ("staff", "staff"),
                    ("staff1", "staff1"),
                    ("my_staff", "my_staff"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
