# Generated by Django 6.0.3 on 2026-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0007_alter_consult_agent_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='agent_incharge',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
